index:
    path: /
    controller: App\Controller\HomeController

monitoring_transactions:
    path: /api/v1/monitoring/transactions
    controller: App\Controller\Monitoring\TransactionsController

monitoring_hooks:
    path: /api/v1/monitoring/hooks
    controller: App\Controller\Monitoring\HooksController

monitoring_users:
    path: /api/v1/monitoring/users
    controller: App\Controller\Monitoring\UsersController

# Lemonway
lemonway_prepare:
    path: /api/v1/lemonway/MoneyInWebInit
    methods: [POST]
    controller: App\Controller\Payment\PrepareController
    defaults:
        gatewayName: App\Lemonway\Lemonway

lemonway_checkout:
    path: /api/v1/lemonway
    methods: [GET]
    controller: App\Controller\Payment\CheckoutController
    defaults:
        gatewayName: App\Lemonway\Lemonway

lemonway_capture:
    path: /api/v1/lemonway
    methods: [POST]
    controller: App\Controller\Payment\CaptureController
    defaults:
        gatewayName: App\Lemonway\Lemonway

lemonway_transaction:
    path: /api/v1/lemonway/GetMoneyInTransDetails
    methods: [POST]
    controller: App\Controller\Payment\TransactionController
    defaults:
        gatewayName: App\Lemonway\Lemonway

# Smoney
smoney_prepare:
    path: /api/v1/smoney/payins/cardpayments
    methods: [POST]
    controller: App\Controller\Payment\PrepareController
    defaults:
        gatewayName: App\Smoney\Smoney

smoney_checkout:
    path: /api/v1/smoney
    methods: [GET]
    controller: App\Controller\Payment\CheckoutController
    defaults:
        gatewayName: App\Smoney\Smoney

smoney_capture:
    path: /api/v1/smoney
    methods: [POST]
    controller: App\Controller\Payment\CaptureController
    defaults:
        gatewayName: App\Smoney\Smoney

smoney_transaction:
    path: /api/v1/smoney/payins/cardpayments/{reference}
    methods: [GET]
    controller: App\Controller\Payment\TransactionController
    defaults:
        gatewayName: App\Smoney\Smoney

smoney_create_user:
    path: /api/v1/smoney/users
    methods: [POST]
    controller: App\Controller\Wallet\CreateWalletController
    defaults:
        gatewayName: App\Smoney\Smoney

smoney_user:
    path: /api/v1/smoney/users/company-{id}
    methods: [GET]
    controller: App\Controller\Wallet\WalletController
    defaults:
        gatewayName: App\Smoney\Smoney

# Mangopay
mangopay_prepare:
    path: /api/v1/mangopay/v2.01/wizaplace/payins/card/web/
    methods: [POST]
    controller: App\Controller\Payment\PrepareController
    defaults:
        gatewayName: App\Mangopay\Mangopay

mangopay_checkout:
    path: /api/v1/mangopay/checkout
    methods: [GET]
    controller: App\Controller\Payment\CheckoutController
    defaults:
        gatewayName: App\Mangopay\Mangopay

mangopay_capture:
    path: /api/v1/mangopay
    methods: [POST]
    controller: App\Controller\Payment\CaptureController
    defaults:
        gatewayName: App\Mangopay\Mangopay

mangopay_transaction:
    path: /api/v1/mangopay/v2.01/wizaplace/payins/{id}
    methods: [GET]
    controller: App\Controller\Payment\TransactionController
    defaults:
        gatewayName: App\Mangopay\Mangopay

mangopay_create_user:
    path: /api/v1/mangopay/v2.01/wizaplace/users/natural
    methods: [POST]
    controller: App\Controller\Wallet\CreateWalletController
    defaults:
        gatewayName: App\Mangopay\Mangopay

mangopay_wallets:
    path: /api/v1/mangopay/v2.01/wizaplace/users/{userId}/wallets
    methods: [GET]
    controller: App\Controller\Wallet\WalletsController
    defaults:
        gatewayName: App\Mangopay\Mangopay

mangopay_create_wallet:
    path: /api/v1/mangopay/v2.01/wizaplace/wallets
    methods: [POST]
    controller: App\Controller\Wallet\CreateWalletController
    defaults:
        gatewayName: App\Mangopay\Mangopay

mangopay_user:
    path: /api/v1/mangopay/v2.01/wizaplace/users/{id}
    methods: [GET]
    controller: App\Controller\Wallet\WalletController
    defaults:
        gatewayName: App\Mangopay\Mangopay

mangopay_oauth:
    path: /api/v1/mangopay/v2.01/oauth/token
    methods: [POST]
    controller: App\Controller\AuthController
    defaults:
        gatewayName: App\Mangopay\Mangopay
