#index:
#    path: /
#    controller: App\Controller\DefaultController::index

lemonway_moneyinwebinit:
    path: /api/v1/lemonway/MoneyInWebInit
    methods: [POST]
    controller: App\Controller\Lemonway\MoneyInWebInitController

lemonway_moneyintoken:
    path: /api/v1/lemonway
    methods: [GET]
    controller: App\Controller\Lemonway\MoneyInTokenController

lemonway_postmoneyintoken:
    path: /api/v1/lemonway
    methods: [POST]
    controller: App\Controller\Lemonway\PostMoneyInTokenController

lemonway_getmoneyintransdetails:
    path: /api/v1/lemonway/GetMoneyInTransDetails
    methods: [POST]
    controller: App\Controller\Lemonway\GetMoneyInTransDetailsController

mangopay_prepare:
    path: /api/v1/mangopay/v2.01/wizaplace/payins/card/web/
    methods: [POST]
    controller: App\Controller\Mangopay\PrepareController

mangopay_checkout:
    path: /api/v1/mangopay/checkout
    methods: [GET]
    controller: App\Controller\Mangopay\CheckoutController

mangopay_capture:
    path: /api/v1/mangopay
    methods: [POST]
    controller: App\Controller\Mangopay\CaptureController

mangopay_transaction:
    path: /api/v1/mangopay/v2.01/wizaplace/payins/{id}
    methods: [GET]
    controller: App\Controller\Mangopay\TransactionController

mangopay_create_user:
    path: /api/v1/mangopay/v2.01/wizaplace/users/natural
    methods: [POST]
    controller: App\Controller\Mangopay\CreateWalletController

mangopay_wallets:
    path: /api/v1/mangopay/v2.01/wizaplace/users/{userId}/wallets
    methods: [GET]
    controller: App\Controller\Mangopay\WalletsController

mangopay_create_wallet:
    path: /api/v1/mangopay/v2.01/wizaplace/wallets
    methods: [POST]
    controller: App\Controller\Mangopay\CreateWalletController

mangopay_user:
    path: /api/v1/mangopay/v2.01/wizaplace/users/{id}
    methods: [GET]
    controller: App\Controller\Mangopay\WalletController

mangopay_oauth:
    path: /api/v1/mangopay/v2.01/oauth/token
    methods: [POST]
    controller: App\Controller\AuthController
